n = 0:1:10;
h = 10*2.^n;
w = -2*pi:2*pi/100 : 2*pi;
b = exp(-j).^(n'*w);
H = h*b;
subplot(3,1,1);
stem(n,h);
title("Impulse Response");
xlabel("No. of samples");
ylabel("h[n]");
grid on ;
hold on ;
subplot(3,1,2);
plot(w,abs(H));
title("Magnitude response");
xlabel("freaquency");
ylabel("|h(w)|");
grid on;
hold on;
subplot(3,1,3);
plot(w,angle(H));
title("Phase response");
xlabel("Freaquency");
ylabel("Phase response");
grid on;
hold on ;
