A = 1;
f = 50;
t = 0:0.00001:(5/f);
xc  = A*sin(2*pi*f*t);
fs = 1000;
td = 0:(1/fs): (5/f);
xd = A*sin(2*pi*f*td);
amp = max(abs(xd));
N =3;
delta = (amp*2)/ (2^N);
xq = delta*floor(xd/delta);
subplot(3,1,1);
stairs(td,xq);
xlabel('Time (s)');
ylabel('Quantized Amplitude');
title('Quantized Signal');
subplot(3,1,2);
plot(t, xc);
xlabel('Time (s)');
ylabel('Amplitude');
title('Original Signal');
error = xd-xq;
subplot(3,1,3);
plot(td,error);
xlabel('Time (s)');
ylabel('Error Amplitude');
title('Quantization Error');
