% SAMPLING ;
A = 1;
f = 50;
t = 0:0.00001:(5/f);
xc  = A*sin(2*pi*f*t);
fs = 1000;
td = 0:(1/fs): (5/f);
xd = A*sin(2*pi*f*td);
subplot(4,1,1);
plot(t,xc);
title("Continuous Sine wave");
xlabel("No. of Samples");
ylabel("Amplitude");
subplot(4,1,2);
stem(td,xd,'r');
title("Sampled Sine wave");
xlabel("No. of Samples");
ylabel("Amplitude");
xr = interp1(td,xd,t,'previous');
se = xc-xr;
subplot(4,1,3);
plot(t, xr, 'g');
title("Interpolated Sine wave");
xlabel("No. of Samples");
ylabel("Amplitude");
subplot(4,1,4);
plot(t, se, 'b');
title("error signal");
xlabel("No. of Samples");
ylabel("Amplitude");
