A = 1;
f = 50;
fs_high = 1000;
%sampling rate;
t_high  = 0:1/fs_high :0.06;
x_analog = A*sin(2*pi*f*t_high);
subplot(4,2,1);
plot(t_high,x_analog,'b','LineWidth',1.5);
title('Original(Analog Signal)');
xlabel('Time');
ylabel('Amplitude');
grid on ;
fs1=200;
t1 = 0:1/fs1:0.06;
x1 = A*sin(2*pi*f*t1);
subplot(4,2,2);
stem(t1, x1, 'r', 'LineWidth', 1.5);
title('Sampled Signal at 200 Hz');
xlabel('Time');
ylabel('Amplitude');
grid on;
fs2=60;
t2 = 0:1/fs2:0.06;
x2 = A*sin(2*pi*f*t2);
subplot(4,2,3);
stem(t2, x2, 'g', 'LineWidth', 1.5);
title('Sampled Signal at 60 Hz');
xlabel('Time');
ylabel('Amplitude');
grid on;
fs3=100;
t3 = 0.001:1/fs3:0.061;
x3 = A*sin(2*pi*f*t3);
subplot(4,2,4);
stem(t3, x3, 'm', 'LineWidth', 1.5);
title('Sampled Signal at 100 Hz');
xlabel('Time');
ylabel('Amplitude');
grid on;
%  Quatization;
t = 0:0.00001:(5/f);
xc  = A*sin(2*pi*f*t);
fs = 1000;
td = 0:(1/fs): (5/f);
xd = A*sin(2*pi*f*td);
amp = max(abs(xd));
N1 =2;
delta1 = (amp*2)/ (2^N1);
xq1 = delta1*floor(xd/delta1);
N2 =4;
delta2 = (amp*2) / (2^N2);
xq2 = delta2 * floor(xd / delta2);
% Plot quantized signals
subplot(4,2,5);
stairs(td, xq1, 'c', 'LineWidth', 1.5);
title('Quantized Signal with N=2');
xlabel('Time');
ylabel('Quantized Amplitude');
grid on;
% Plot quantized signal with N=4
subplot(4,2,6);
stairs(td, xq2, 'y', 'LineWidth', 1.5);
title('Quantized Signal with N=4');
xlabel('Time');
ylabel('Quantized Amplitude');
grid on;
error1 = xd-xq1;
error2 = xd-xq2;
subplot(4,2,7);
plot(td, error1, 'k', 'LineWidth', 1.5);
title('Quantization Error with N=2');
xlabel('Time');
ylabel('Error Amplitude');
grid on;
subplot(4,2,8);
plot(td, error2, 'm', 'LineWidth', 1.5);
title('Quantization Error with N=4');
xlabel('Time');
ylabel('Error Amplitude');
grid on;
